---
title: "Data_import"
output: github_document
---

```{r setup}
library(tidyverse)
library(readxl)
library(haven)
```

## Read in some data

Read in the litter dataset.

```{r}
litters_df <- read_csv("./data/FAS_litters.csv")
litters_df <- janitor::clean_names(litters_df) # using function from janitor without loading
                                                # the whole package
```

## Take a look at the data

printing in the console.

```{r}
litters_df
```

```{r}
head(litters_df)
tail(litters_df)
```

```{r}
skimr::skim(litters_df)
```

##Options to read csv

check out '?read_csv' for more info. 

##Other file formats.

Read in an excel file.

```{r}
mlb_df <- read_excel("./data/mlb11.xlsx", range = "A1:F7")
```

Read in a SAS file.

```{r}
pulse_df <- read_sas("./data/public_pulse_data.sas7bdat")
```

##comparison with Base R

what about `read.csv` ... ?

```{r} 
litters_base <- read.csv("./data/FAS_litters.csv")
litters_readr <- read_csv("./data/FAS_litters.csv")
```

## Exporting data 

Export the mlb sub-table.

```{r}
write_csv(mlb_df, "./data/mlb_subtable.csv")
```

